SSID List for Wireless Windows machines
cloudmesh/cloudmesh-pi-burn pull request #62
Opened 2022-05-14 13:34 UTC by dkkolli

Give users list of ssids for windows users to choose from if ssid is not entered initially in 
`cms burn raspberry`
command 

Could not get Printer.write()  to work instead of printing list.

2022-05-14 13:37 UTC, dkkolli commented
Updating for wired connections also

2022-05-14 21:31 UTC, laszewsk commented
HOw are you able to update your pull request into cloudmesh?
https://github.com/cloudmesh/cloudmesh-pi-burn/pull/62
I like to identify if the pull request you made is done by you or done in some other way. As far as i can tell you do not have right to merge pull requests, but I may be wrong ...

2022-05-16 20:43 UTC, dkkolli commented
If using a wireless windows machine, provides list of wifi networks:
+-------+-----------------+
| Index | Host            |
+-------+-----------------+
|     0 | eduroam         |
|     1 | iPhone          |
|     2 | IU Guest        |
|     3 | IU Secure       |
|     4 | GNXS-9959       |
|     5 | Bluegreen_GUEST |
|     6 | ZyXEL7A2C00     |
|     7 | MetroDK         |
|     8 | 2WIRE131        |
+-------+-----------------+
Enter ssid from list:

If using a wired windows machine, lets user know machine is not configured for wifi.

2022-05-16 20:53 UTC, laszewsk commented
I think on osx we do not need a list we simply look up what the wifi is that the laptop uses. is ther not just such a function. otherwise shoudl we not implement a function 

list_wifi() and if the current wifi cfrom the laaptop can not pe obtained in windows we use the list function ...
so i would split this functionality.

2022-05-16 20:53 UTC, laszewsk commented
can you try 
```Netsh wlan show profiles```

2022-05-16 20:54 UTC, laszewsk commented
i think what you look for is
```Netsh WLAN show interfaces```

2022-05-16 20:58 UTC, laszewsk commented
pseudocode:
r = Shell.run("Netsh WLAN show interfaces").strip().splitlines
ssid = SHell.cm_grep(r, "SSID").split(":")[0].strip()

again i do not have a windows machine so I do this in my head ... thus no gurantees.

2022-05-16 21:04 UTC, laszewsk requested changes
pseudocode:
r = Shell.run("Netsh WLAN show interfaces").strip().splitlines()
ssid = SHell.cm_grep(r, "SSID").split(":")[0].strip()

again i do not have a windows machine so I do this in my head ... thus no gurantees.

2022-05-19 13:16 UTC, laszewsk reviewed
did we not say that interfaces shows the current ssid?

2022-05-24 19:39 UTC, laszewsk commented
JP will check and review the newest version of the code. 
- [ ] I think we implemented the ssid find
- [ ] i think we implemented country code
- [ ] I suggested to implement cloudmesh.common.util.getpass so it works on all architectures including WIndows. this way we can use this getpass and not the one from python as its documented the windows version is not implementing getpass

2022-05-24 21:06 UTC, laszewsk approved these changes

2022-05-24 21:06 UTC, laszewsk commented
there are conflicts

2022-05-24 21:08 UTC, laszewsk commented
I suggest not to modify this pull request, but to just do its completely from scratch and than we just close this pull requests much easier

2022-05-24 21:10 UTC, closed without merging